"""Build and measure one RTL core per held-out design point.

For each point this writes a variant makefile.inc, forces a clean bsc
elaboration, rebuilds the Verilator simulator, and runs the benchmarks. The
measured cycle counts are the ground truth the model is scored against.

Safety properties, because this mutates the working tree:

* The original makefile.inc and bin/out are saved before anything runs and
  restored on exit, including on Ctrl-C or a crash.
* Results are written per point, so an interrupted sweep resumes where it
  stopped (``--resume``, on by default).
* A build or run failure is recorded and the sweep continues to the next point.

Usage::

    ./holdout/rtl_sweep.py                     # full sweep, resumable
    ./holdout/rtl_sweep.py --points byp1 btb8  # subset
    ./holdout/rtl_sweep.py --dry-run           # print the plan, build nothing

Note that makefile.inc is generated by ``soc_config``. Do not re-run soc_config
while a sweep is in flight; it will clobber the variant defines.
"""

from __future__ import annotations

from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path
import argparse
import atexit
import json
import os
import shutil
import signal
import subprocess
import sys
import time

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from design_points import (  # noqa: E402
    BY_NAME,
    DEFAULT_ORDER,
    DesignPoint,
    describe,
    render_variant,
)
from trace import parse_app_log_metrics  # noqa: E402

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
MAKEFILE = REPO / "makefile.inc"
BENCH_OUT = REPO / "benchmarks" / "output"
RUNS = HERE / "runs"
#: Pristine copy of makefile.inc, saved by TreeGuard before the first build.
#: Every variant is rendered from this, never from the working-tree file.
BASELINE_MAKEFILE = RUNS / ".baseline" / "makefile.inc.orig"
TOOL_PATH = f"{Path.home()}/tools/bin:{Path.home()}/tools/bsc/bin:" + os.environ.get("PATH", "")

#: Benchmarks to run per design point. Dhrystone is cheap enough to trace, so
#: it carries the per-point Delta-t validation; CoreMark is app_log only
#: because its trace is ~1 GB per point.
#: ``marker`` is the last line the benchmark prints to app_log. The simulator
#: does not self-terminate -- it writes app_log and then spins -- so the sweep
#: watches for the marker and stops it, instead of burning the full timeout on
#: every one of two benchmarks times twelve design points.
BENCHMARKS = {
    "dhrystone": {
        "make": ["dhrystone", "ITERATIONS=500"],
        "rtldump": True,
        "marker": "IPC_MEASURE",
    },
    "coremark": {
        "make": ["coremarks", "ITERATIONS=40"],
        "rtldump": False,
        "marker": "CoreMark 1.0 :",
    },
    "fpbench": {
        "make": ["fpbench", "ITERATIONS=100"],
        "rtldump": True,
        "marker": "IPC_MEASURE",
    },
}


def log(message: str) -> None:
    stamp = datetime.now().strftime("%H:%M:%S")
    print(f"[{stamp}] {message}", flush=True)


def run(cmd: list[str], cwd: Path, timeout: int, log_path: Path) -> tuple[int, float]:
    """Run a command, tee output to a log file, return (exit code, seconds)."""
    env = dict(os.environ, PATH=TOOL_PATH, SHAKTI_HOME=str(REPO))
    start = time.time()
    with log_path.open("w", encoding="utf-8", errors="replace") as handle:
        handle.write(f"$ {' '.join(cmd)}\n(cwd={cwd})\n\n")
        handle.flush()
        try:
            proc = subprocess.run(
                cmd, cwd=cwd, env=env, stdout=handle, stderr=subprocess.STDOUT, timeout=timeout
            )
            code = proc.returncode
        except subprocess.TimeoutExpired:
            handle.write(f"\n*** TIMEOUT after {timeout}s ***\n")
            code = 124
    return code, time.time() - start


class TreeGuard:
    """Save and restore everything the sweep mutates."""

    def __init__(self, backup_dir: Path):
        self.backup_dir = backup_dir
        self.backup_dir.mkdir(parents=True, exist_ok=True)
        self.makefile_backup = backup_dir / "makefile.inc.orig"
        self.out_backup = backup_dir / "out.orig"
        self.trace_backup = backup_dir / "coremark-trace"
        self.restored = False

    def save(self) -> None:
        if not self.makefile_backup.exists():
            shutil.copy2(MAKEFILE, self.makefile_backup)
        sim = REPO / "bin" / "out"
        if sim.exists() and not self.out_backup.exists():
            shutil.copy2(sim, self.out_backup)
        # The pre-existing CoreMark trace is ~1 GB and expensive to regenerate,
        # and run_benchmark() clears rtl*.dump before every run. Move it out of
        # harm's way rather than letting the first benchmark delete it.
        self.trace_backup.mkdir(parents=True, exist_ok=True)
        for dump in sorted(BENCH_OUT.glob("rtl*.dump")):
            dest = self.trace_backup / dump.name
            if dest.exists():
                continue
            shutil.move(str(dump), str(dest))
            log(f"moved pre-existing {dump.name} to {dest}")
        log(f"saved baseline makefile.inc and bin/out to {self.backup_dir}")

    def restore(self) -> None:
        if self.restored:
            return
        self.restored = True
        if self.makefile_backup.exists():
            shutil.copy2(self.makefile_backup, MAKEFILE)
            log("restored baseline makefile.inc")
        log(
            "NOTE: bin/out and build/ still hold the last design point built. "
            f"The baseline simulator is preserved at {self.out_backup}; "
            "re-run with --points baseline to rebuild it in place."
        )
        if self.trace_backup.exists() and any(self.trace_backup.iterdir()):
            log(f"NOTE: the original CoreMark trace is at {self.trace_backup}")


def clean_intermediates() -> None:
    """bsc caches .bo files by source hash, not by -D defines.

    Without this, a variant silently reuses the baseline's elaborated modules
    and the "design point" is not actually built. This has bitten this project
    before (the mhpm event-vector width change).
    """
    for sub in ("build/hw/intermediate", "build/hw/verilog", "obj_dir"):
        target = REPO / sub
        if target.exists():
            shutil.rmtree(target)
        target.mkdir(parents=True, exist_ok=True)


def build(point_dir: Path, timeout: int) -> tuple[bool, dict]:
    timings = {}
    code, secs = run(["make", "generate_verilog"], REPO, timeout, point_dir / "build-bsc.log")
    timings["bsc_seconds"] = round(secs, 1)
    if code != 0:
        return False, timings | {"failed_stage": "generate_verilog", "exit_code": code}
    code, secs = run(
        ["make", "link_verilator", "generate_boot_files"],
        REPO,
        timeout,
        point_dir / "build-verilator.log",
    )
    timings["verilator_seconds"] = round(secs, 1)
    if code != 0:
        return False, timings | {"failed_stage": "link_verilator", "exit_code": code}
    return True, timings


def run_sim(cmd: list[str], cwd: Path, marker: str, log_path: Path, timeout: int,
            grace: float = 8.0) -> tuple[str, float]:
    """Run the simulator until app_log shows the benchmark's final line.

    The testbench only calls $finish on a `j .` self-loop, which the benchmarks
    never reach: they print their results and then spin. Waiting for the
    timeout would cost an hour per benchmark per design point, so poll app_log
    for the marker instead and stop the simulator once it appears. The grace
    period lets the last of the commit trace reach disk.
    """
    env = dict(os.environ, PATH=TOOL_PATH, SHAKTI_HOME=str(REPO))
    app_log = cwd / "app_log"
    start = time.time()
    with log_path.open("w", encoding="utf-8", errors="replace") as handle:
        handle.write(f"$ {' '.join(cmd)}\n(cwd={cwd}, marker={marker!r})\n\n")
        handle.flush()
        proc = subprocess.Popen(cmd, cwd=cwd, env=env, stdout=handle, stderr=subprocess.STDOUT)
        seen_at: float | None = None
        try:
            while True:
                if proc.poll() is not None:
                    return "exited", time.time() - start
                if seen_at is None and app_log.exists():
                    try:
                        if marker in app_log.read_text(encoding="utf-8", errors="replace"):
                            seen_at = time.time()
                    except OSError:
                        pass
                elif seen_at is not None and time.time() - seen_at >= grace:
                    proc.terminate()
                    try:
                        proc.wait(timeout=30)
                    except subprocess.TimeoutExpired:
                        proc.kill()
                    return "marker", time.time() - start
                if time.time() - start > timeout:
                    proc.kill()
                    proc.wait(timeout=30)
                    handle.write(f"\n*** TIMEOUT after {timeout}s without marker {marker!r} ***\n")
                    return "timeout", time.time() - start
                time.sleep(1.0)
        finally:
            if proc.poll() is None:
                proc.kill()


def run_benchmark(name: str, spec: dict, point_dir: Path, timeout: int) -> dict:
    code, secs = run(
        ["make", "-C", "benchmarks"] + spec["make"], REPO, 900, point_dir / f"{name}-compile.log"
    )
    if code != 0:
        return {"status": "compile_failed", "exit_code": code}

    for stale in ("app_log", "rtl.dump", "rtl1.dump"):
        (BENCH_OUT / stale).unlink(missing_ok=True)
    for link in REPO.joinpath("bin").iterdir():
        target = BENCH_OUT / link.name
        target.unlink(missing_ok=True)
        target.symlink_to(link)

    cmd = ["./out"] + (["+rtldump"] if spec["rtldump"] else [])
    how, secs = run_sim(cmd, BENCH_OUT, spec["marker"], point_dir / f"{name}-sim.log", timeout)

    metrics = parse_app_log_metrics(BENCH_OUT / "app_log")
    if metrics is None:
        return {"status": "no_metrics", "stopped_by": how, "sim_seconds": round(secs, 1)}

    result = {
        "status": "ok",
        "cycles": metrics.cycles,
        "instret": metrics.instret,
        "runs": metrics.runs,
        "stopped_by": how,
        "sim_seconds": round(secs, 1),
    }
    shutil.copy2(BENCH_OUT / "app_log", point_dir / f"{name}-app_log")
    if spec["rtldump"]:
        dumps = sorted(BENCH_OUT.glob("rtl*.dump"))
        kept = []
        for dump in dumps:
            dest = point_dir / dump.name
            shutil.copy2(dump, dest)
            kept.append(dest.name)
        result["traces"] = kept
    return result


def sweep_point(point: DesignPoint, args: argparse.Namespace) -> dict:
    point_dir = RUNS / point.name
    point_dir.mkdir(parents=True, exist_ok=True)
    result_path = point_dir / "result.json"

    if args.resume and result_path.exists():
        existing = json.loads(result_path.read_text())
        if existing.get("status") == "ok":
            log(f"{point.name}: already done, skipping")
            return existing

    log(f"{point.name}: {describe(point)}  [{point.mechanism}]")
    # Always render from the pristine baseline. Rendering from MAKEFILE would
    # compound edits, because MAKEFILE holds the previous point's variant.
    source = BASELINE_MAKEFILE if BASELINE_MAKEFILE.exists() else MAKEFILE
    variant = render_variant(source, point)
    (point_dir / "makefile.inc").write_text(variant, encoding="utf-8")

    record: dict = {
        "name": point.name,
        "edits": describe(point),
        "mechanism": point.mechanism,
        "why": point.why,
        "expect": point.expect,
        "tags": list(point.tags),
        "started": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    }

    MAKEFILE.write_text(variant, encoding="utf-8")
    clean_intermediates()

    ok, timings = build(point_dir, args.build_timeout)
    record.update(timings)
    if not ok:
        record["status"] = "build_failed"
        log(f"{point.name}: BUILD FAILED at {timings.get('failed_stage')} "
            f"(see {point_dir}/build-*.log)")
        result_path.write_text(json.dumps(record, indent=2), encoding="utf-8")
        return record
    log(f"{point.name}: built in {timings['bsc_seconds']:.0f}s bsc + "
        f"{timings['verilator_seconds']:.0f}s verilator")

    record["benchmarks"] = {}
    for name, spec in BENCHMARKS.items():
        if args.benchmarks and name not in args.benchmarks:
            continue
        outcome = run_benchmark(name, spec, point_dir, args.sim_timeout)
        record["benchmarks"][name] = outcome
        if outcome["status"] == "ok":
            ipc = (outcome["instret"] / outcome["cycles"]) if outcome.get("instret") else None
            ipc_text = f" ipc={ipc:.4f}" if ipc else ""
            log(f"{point.name}: {name} cycles={outcome['cycles']:,}{ipc_text} "
                f"({outcome['sim_seconds']:.0f}s)")
        else:
            log(f"{point.name}: {name} {outcome['status'].upper()}")

    good = [b for b in record["benchmarks"].values() if b["status"] == "ok"]
    record["status"] = "ok" if good else "run_failed"
    record["finished"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
    result_path.write_text(json.dumps(record, indent=2), encoding="utf-8")
    return record


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--points", nargs="*", default=None, help="subset of design points to build")
    parser.add_argument("--benchmarks", nargs="*", default=None, choices=list(BENCHMARKS))
    parser.add_argument("--build-timeout", type=int, default=7200)
    parser.add_argument("--sim-timeout", type=int, default=3600)
    parser.add_argument("--no-resume", dest="resume", action="store_false")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    names = args.points or list(DEFAULT_ORDER)
    unknown = [n for n in names if n not in BY_NAME]
    if unknown:
        parser.error(f"unknown design point(s): {', '.join(unknown)}")
    points = [BY_NAME[n] for n in names]

    if args.dry_run:
        print(f"{'point':<12} {'edits':<44} mechanism")
        for point in points:
            print(f"{point.name:<12} {describe(point):<44} {point.mechanism}")
        print(f"\n{len(points)} builds. Each needs a clean bsc elaboration plus a "
              f"Verilator link.")
        return 0

    RUNS.mkdir(parents=True, exist_ok=True)
    guard = TreeGuard(RUNS / ".baseline")
    guard.save()
    atexit.register(guard.restore)
    for sig in (signal.SIGINT, signal.SIGTERM):
        signal.signal(sig, lambda *_: sys.exit(130))

    started = time.time()
    records = []
    for index, point in enumerate(points, start=1):
        log(f"=== [{index}/{len(points)}] {point.name} ===")
        records.append(sweep_point(point, args))

    guard.restore()

    summary = RUNS / "sweep.json"
    summary.write_text(
        json.dumps(
            {
                "generated": datetime.now(timezone.utc).isoformat(timespec="seconds"),
                "elapsed_seconds": round(time.time() - started, 1),
                "points": records,
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    ok = sum(1 for r in records if r.get("status") == "ok")
    log(f"done: {ok}/{len(records)} points measured in {(time.time()-started)/60:.0f} min "
        f"-> {summary}")
    return 0 if ok == len(records) else 1


if __name__ == "__main__":
    raise SystemExit(main())
